---
user_dir:    # where to override settings with a custom config.yaml file and, for example, add custom frameworks, benchmark definitions or framework modules: set by caller (runbenchmark.py).
input_dir:   # where to find the input datasets, set by caller (runbenchmark.py).
output_dir:  # where logs and results are saved by default: set by caller (runbenchmark.py).
root_dir:    # app root dir: set by caller (runbenchmark.py)

script:     # calling script: set by caller (runbenchmark.py)
run_mode:   # target run mode (local, docker): set by caller (runbenchmark.py)
sid:        # session id: set by caller (runbenchmark.py)
job_history:    # file containing the list of jobs already executed: set by caller (runbenchmark.py)

test_mode: false        # if set to true, some additional checks are executed at runtime.
seed: auto              # default global seed (used if not set in task definition), can be one of:
                        #  `auto`: a global seed will be generated and passed to all jobs.
                        #  `none`: no seed will be provided (seed left to framework's responsibility).
                        #   any int32 to pass a fixed seed to the jobs.
token_separator: '.'    # set to '_' for backwards compatibility.
                        # This separator is used to generate directory structure and files,
                        # however the '_' separator makes the parsing of those names more difficult as it's also used in framework names, task names...
archive: []       # list of output folders that should be archived by default.
                  # Note that when used in a parallel setting where the same framework is invoked multiple times in
                  # the same second, archiving directories may lead to errors due to race conditions (#672).

setup:                   # configuration namespace for the framework setup phase.
  live_output: true      # set to true to stream the output of setup commands, if false they are only printed when setup is complete.
  activity_timeout: 600  # when using live output, subprocess will be considered as hanging if nothing was printed during this activity time.
                         # No effect is live_output is set to 'False'.

frameworks:              # configuration namespace for the frameworks definitions.
  definition_file:       # list of yaml files describing the frameworks base definitions.
    - '{root}/resources/frameworks.yaml'
  root_module: frameworks     # the default python module under which the frameworks modules are defined.
  allow_duplicates: false     # if true, the last definition is used.
  tags: ['stable', 'latest']  # the list of supported tags when looking up frameworks:
                              # for example frmwk:latest will look for framework frmwk in a frameworks_latest.yaml file if present.

benchmarks:                     # configuration namespace for the benchmarks definitions.
  definition_dir:               # list of directories containing the benchmarks yaml definitions.
    - '{root}/resources/benchmarks'
  constraints_file:             # list of yaml files describing the benchmarks runtime constraints.
    - '{root}/resources/constraints.yaml'
  on_unfulfilled_constraint: 'fail'  # one of ('auto', 'warn', 'fail'), used when checking the os resources if one memory/core/volume constraint can not be fulfilled:
                                     #   if 'auto' benchmark, will fail on important unfulfilled constraints (cores, memory) on non local modes, and warn otherwise.
                                     #   if 'warn' only a warning message will be emitted;
                                     #   if 'fail' the benchmark will be immediately interrupted;
  os_mem_size_mb: 2048          # the default amount of memory left to the OS when task assigned memory is computed automatically.
  os_vol_size_mb: 2048          # the default amount of volume left to the OS when task volume memory is verified.
  overhead_time_multiplier: 2   # multiplier to the time allowed for the job to complete before sending an interruption signal. Default is 2 if unspecified.
  overhead_time_seconds: 3600   # amount of additional time allowed for the job to complete before sending an interruption signal.
                                # the total allowed time is min(value * overhead_time_multiplier, value + overhead_time_seconds)
  metrics:                      # default metrics by dataset type (as listed by amlb.data.DatasetType),
                                # only the first metric is optimized by the frameworks,
                                # the others are computed only for information purpose.
    binary: ['auc', 'logloss', 'acc', 'balacc']     # available metrics: auc (AUC), acc (Accuracy), balacc (Balanced Accuracy), pr_auc (Precision Recall AUC), logloss (Log Loss), f1, f2, f05 (F-beta scores with beta=1, 2, or 0.5), max_pce, mean_pce (Max/Mean Per-Class Error).
    multiclass: ['logloss', 'acc', 'balacc']        # available metrics: same as for binary, except auc, replaced by auc_ovo (AUC One-vs-One), auc_ovr (AUC One-vs-Rest). AUC metrics and F-beta metrics are computed with weighted average.
    regression: ['rmse', 'r2', 'mae']               # available metrics: mae (Mean Absolute Error), mse (Mean Squared Error), msle (Mean Squared Logarithmic Error), rmse (Root Mean Square Error), rmsle (Root Mean Square Logarithmic Error), r2 (R^2).
    timeseries: ['mase', 'mape', 'smape', 'wape', 'rmse', 'mse', 'mql', 'wql', 'sql']  # available metrics: mase (Mean Absolute Scaled Error), mape (Mean Absolute Percentage Error), smape (Symmetric Mean Absolute Percentage Error), wape (Weighted Absolute Percentage Error), rmse (Root Mean Square Error), mse (Mean Square Error), mql (Mean Quantile Loss), wql (Weighted Quantile Loss), sql (Scaled Quantile Loss).

  defaults:            # the default constraints, usually overridden by a constraint.
    folds: 10          # the amount of fold-runs executed for each dataset.
    max_runtime_seconds: -1     # default time allocated to the framework to train a model.
    cores: -1                   # default amount of cores used for each automl task. If <= 0, will try to use all cores.
    max_mem_size_mb: -1         # default amount of memory assigned to each automl task. If <= 0, then the amount of memory is computed from os available memory.
    min_vol_size_mb: -1         # default minimum amount of free space required on the volume. If <= 0, skips verification.
    quantile_levels: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]  # default quantile_levels for timeseries problem type

job_scheduler:           # configuration namespace
  exit_on_job_failure:   # if true, the entire run will be aborted on the first job failure (mainly used for testing) : set by caller (runbenchmark.py)
  parallel_jobs: 1       # the number of jobs being run in parallel in a benchmark session, set by caller (runbenchmark.py)
  max_parallel_jobs: 10  # safety limit for parallel jobs. Defaults to 10 to allow running the usual 10 folds in parallel with no problem.
  delay_between_jobs: 5  # delay in seconds between each parallel job start

monitoring:               # configuration namespace describing the basic monitoring features: currently, the app only logs each statistic at a given interval.
  interval_seconds: 120   # set to <= 0 to disable monitoring
  statistics: ['cpu', 'sys_memory', 'volume'] # the monitoring values currently available are:
                          # cpu : monitors global cpu usage; higher verbosity provides cpu usage per core.
                          # sys_memory : monitors the global memory usage; higher verbosity increases the precision: from percent (v=0) to bytes (v>=2).
                          # volume : monitors the volume usage; higher verbosity increases the precision, from percent (v=0) to bytes (v>=2).
                          # proc_memory : monitors the memory usage on the main process; higher verbosity adds some details.
                          # sub_proc_memory : monitors the memory usage on the framework subprocess running in its virtual environment; available only if the main process is run as root.
  verbosity: 0            # from 0 to 3, higher verbosity provides more details for each statistic.

results:                 # configuration namespace for the results.csv file.
  error_max_length: 200  # the max length of the error message as rendered in the results file.
  global_save: true      # set by runbenchmark.py, if true adds the results to the main `results.csv` in the {output.dir}
  global_lock_timeout: 5 # the timeout used to wait for the lock on the global results file.
  incremental_save: true # if true save results after each job., otherwise save results only when all jobs are completed.

inference_time_measurements:  # configuration namespace for performing additional inference time measurements on various batch sizes
  enabled: false
  batch_sizes: [1, 10, 100, 1000, 10000]  # the batch sizes for which inference speed should be measured
  repeats: 10                            # the number of times to repeat the inference measurement for each batch size
  additional_job_time: 300  # the time in seconds that will be added to the maximum job time if inference time is measured
  limit_by_dataset_size: true  # Don't measure inference time on `batch size` if it exceeds the number of rows in the dataset.
                               # E.g., on micro-mass (571 rows) with `batch_sizes` [1, 10, 100, 1000, 10000], only measure [1, 10, 100].

openml:                # configuration namespace for openML.
  apikey: c1994bdb7ecb3c6f3c8f3b35f4b47f1f
  infer_dtypes: False

versions:              # configuration namespace for versions enforcement (libraries versions are usually enforced in requirements.txt for the app and for each framework).
  pip:
  python: 3.11        # the Python minor version that will be used by the application in containers and cloud instances, also used as a based version for virtual environments created for each framework.

container: &container          # parent configuration namespace for container modes.
  minimize_instances: true     # set to true to avoid running multiple container instances on the same machine.
  run_extra_options: ''        # additional options passed to the container exec.
  image:                       # set this value through -Xcontainer.image=my-image to run benchmark with a specific image
  image_defaults:
    author: automlbenchmark
    image:                     # set by container impl based on framework name, lowercase
    tag:                       # set by container impl based on framework version

docker:                        # configuration namespace for docker: it inherits from `container` namespace.
  <<: *container
  run_extra_options: >-
    --shm-size=2048M
  run_as: 'default'    # Sets the user inside the docker container (`docker run -u`), one of:
                       #  * 'user': set as `-u $(id -u):$(id -g)`, only on unix systems.
                       #  * 'root': set as `-u 0:0`
                       #  * 'default': does not set `-u`
                       #  * any string that starts with `-u`, which will be directly forwarded.
                       # Try this setting if you have problems with permissions in docker.
  build_extra_options: ''
